# Generated by Django 3.0.2 on 2022-08-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ativos',
            new_name='Ativo',
        ),
    ]
