# Generated by Django 3.0.2 on 2022-08-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0002_auto_20220831_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='ticker',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
