# Generated by Django 3.0.2 on 2022-08-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0004_auto_20220831_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='id',
        ),
        migrations.AlterField(
            model_name='ativo',
            name='inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='ticker',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
