# Generated by Django 3.0.2 on 2022-09-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0005_auto_20220831_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotaPatrimonial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('cota_patrimonial', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fi_infra.Ativo')),
            ],
        ),
    ]
