# Generated by Django 3.0.2 on 2022-09-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0006_cotapatrimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='juros',
            field=models.CharField(choices=[(1, 'mensal'), (6, 'semestral')], default=1, max_length=1),
        ),
    ]
