# Generated by Django 3.0.2 on 2022-09-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0008_auto_20220902_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotapatrimonial',
            name='patrimonio_liquido',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='cotapatrimonial',
            name='cota_patrimonial',
            field=models.FloatField(default=None),
        ),
    ]
