# Generated by Django 3.0.2 on 2022-09-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0010_auto_20220905_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='gestor',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='nome',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='taxa_adm',
            field=models.FloatField(default=None),
        ),
    ]
