# Generated by Django 3.0.2 on 2022-09-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0011_auto_20220906_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotapatrimonial',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fi_infra.Ativo'),
        ),
    ]
