# Generated by Django 3.0.2 on 2022-09-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi_infra', '0012_auto_20220906_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='gestor',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='taxa_adm',
            field=models.FloatField(default=None, null=True),
        ),
    ]
